-- This script will be automatically executed by Spring Boot on startup with an embedded H2 database.

drop table if exists books;

create table books(
    id int generated by default as identity primary key,
    title varchar(50),
    price decimal(6,2)
);

insert into books(title, price) values
('Advanced Class Design', 190.90),
('Java Programming Language', 50.50);